CREATE TABLE diet_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(16) NOT NULL,
  token_version INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE diet_slot_option (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_name VARCHAR(64) NOT NULL,
  option_value VARCHAR(64) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO diet_slot_option (slot_name, option_value, sort_order) VALUES
  ('mealTime', '午餐', 10), ('mealTime', '晚餐', 20), ('taste', '清淡', 10);

CREATE TABLE meal_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type VARCHAR(16) NOT NULL,
  owner_user_id BIGINT,
  name VARCHAR(128) NOT NULL,
  image_url VARCHAR(1024),
  meal_time VARCHAR(2048) NOT NULL,
  mood VARCHAR(2048) NOT NULL,
  scene VARCHAR(2048) NOT NULL,
  health_goal VARCHAR(2048) NOT NULL,
  cuisine VARCHAR(2048) NOT NULL,
  taste VARCHAR(2048) NOT NULL,
  convenience VARCHAR(2048) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
