CREATE TABLE diet_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(16) NOT NULL,
  token_version INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE diet_slot_option (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_name VARCHAR(64) NOT NULL,
  option_value VARCHAR(64) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO diet_slot_option (slot_name, option_value, sort_order) VALUES
  ('mealTime', '午餐', 10), ('mealTime', '晚餐', 20), ('taste', '清淡', 10);

CREATE TABLE meal_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type VARCHAR(16) NOT NULL,
  owner_user_id BIGINT,
  name VARCHAR(128) NOT NULL,
  image_url VARCHAR(1024),
  meal_time VARCHAR(2048) NOT NULL,
  mood VARCHAR(2048) NOT NULL,
  scene VARCHAR(2048) NOT NULL,
  health_goal VARCHAR(2048) NOT NULL,
  cuisine VARCHAR(2048) NOT NULL,
  taste VARCHAR(2048) NOT NULL,
  convenience VARCHAR(2048) NOT NULL,
  acquisition_mode VARCHAR(16) NOT NULL DEFAULT 'BOTH',
  prep_minutes INT,
  difficulty VARCHAR(16),
  price_min DECIMAL(10,2),
  price_max DECIMAL(10,2),
  default_servings INT NOT NULL DEFAULT 1,
  ingredients_json VARCHAR(8000) NOT NULL,
  steps_json VARCHAR(8000) NOT NULL,
  dine_out_tips VARCHAR(1000),
  substitutes_json VARCHAR(8000) NOT NULL,
  calories INT,
  protein DECIMAL(8,2),
  fat DECIMAL(8,2),
  carbs DECIMAL(8,2),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE TABLE diet_user_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL, memory_type VARCHAR(32) NOT NULL, memory_key VARCHAR(128) NOT NULL,
  memory_value VARCHAR(256) NOT NULL, strength DECIMAL(5,2) NOT NULL DEFAULT 1,
  evidence_count INT NOT NULL DEFAULT 1, source VARCHAR(32) NOT NULL, last_session_id VARCHAR(64),
  created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
  UNIQUE(user_id, memory_type, memory_key, memory_value)
);

CREATE TABLE diet_meal_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL,
  plan_date DATE NOT NULL, meal_period VARCHAR(16) NOT NULL, meal_id BIGINT NOT NULL,
  meal_snapshot VARCHAR(16000) NOT NULL, acquisition_mode VARCHAR(16) NOT NULL,
  servings INT NOT NULL DEFAULT 1, status VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
  created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
  UNIQUE(user_id, plan_date, meal_period)
);

CREATE TABLE diet_meal_checkin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, plan_id BIGINT NOT NULL,
  actual_meal_id BIGINT, actual_meal_name VARCHAR(128), rating INT, satiety INT,
  reason_code VARCHAR(32), note VARCHAR(500), actual_spent DECIMAL(10,2), eaten_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(plan_id)
);

CREATE TABLE diet_shopping_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, week_start DATE NOT NULL,
  sync_version INT NOT NULL DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'DRAFT', synced_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(user_id, week_start)
);

CREATE TABLE diet_shopping_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, list_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL, category VARCHAR(64) NOT NULL, quantity DECIMAL(12,3), unit VARCHAR(32),
  source_meal_ids VARCHAR(8000) NOT NULL, manual BOOLEAN NOT NULL DEFAULT FALSE,
  completed BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
